### ISSUE TITLE
Network recovery breaks TransactionScope

### ISSUE THREAD

**Issue by xorandor** [rebus-org/Rebus.RabbitMq#16]
I've run into an issue when using transactions and recovering from a network outage/disconnect.

I've tested with the following sample code, where Rebus has been configured with multiple endpoints in the connection string. 

```
while(true)
{
 using (var tx = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
 {
  tx.EnlistRebus(); 

  for (int i = 0; i < tmp; i++)
  {
   await bus.Send(new Message1 { Name = "allan" });
  }
  tx.Complete();
 }
}
```

If the RabbitMQ node that Rebus is connected to goes down, normally it would establish a new connection. But when there's a Rebus transaction involved, it breaks the bus instance, rendering it inoperable.

After the disconnect, the following exception is thrown upon exiting the using block:

```
Rebus.Exceptions.RebusApplicationException occurred
  HResult=0x80131500
  Message=Could not 'GetOrAdd' item with key 'rabbitmq-current-model' as type RabbitMQ.Client.IModel
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Rebus.Transport.TransactionContextExtensions.GetOrAdd[TItem](ITransactionContext context, String key, Func`1 newItemFactory)
   at Rebus.RabbitMq.RabbitMqTransport.GetModel(ITransactionContext context)
   at Rebus.RabbitMq.RabbitMqTransport.<SendOutgoingMessages>d__44.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Transport.TransactionContext.<Invoke>d__24.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Transport.TransactionContext.<RaiseCommitted>d__21.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Transport.TransactionContext.<Complete>d__19.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Bus.Advanced.AsyncHelpers.CustomSynchronizationContext.<<Run>b__7_0>d.MoveNext()
   at Rebus.Bus.Advanced.AsyncHelpers.CustomSynchronizationContext.Run()
   at Rebus.Bus.Advanced.AsyncHelpers.RunSync(Func`1 task)
   at Rebus.Transport.RebusTransactionScope.Complete()
   at Rebus.TransactionScopes.TransactionScopeExtensions.AmbientTransactionBridge.Commit(Enlistment enlistment)
   at System.Transactions.VolatileEnlistmentCommitting.EnterState(InternalEnlistment enlistment)
   at System.Transactions.VolatileEnlistmentPrepared.InternalCommitted(InternalEnlistment enlistment)
   at System.Transactions.TransactionStateCommitted.EnterState(InternalTransaction tx)
   at System.Transactions.TransactionStateSPC.EnterState(InternalTransaction tx)
   at System.Transactions.TransactionStateVolatilePhase1.Phase1VolatilePrepareDone(InternalTransaction tx)
   at System.Transactions.Phase1VolatileEnlistment.CheckComplete()
   at System.Transactions.Phase1VolatileEnlistment.FinishEnlistment()
   at System.Transactions.VolatileEnlistmentPreparing.Prepared(InternalEnlistment enlistment)
   at System.Transactions.PreparingEnlistment.Prepared()
   at Rebus.TransactionScopes.TransactionScopeExtensions.AmbientTransactionBridge.Prepare(PreparingEnlistment preparingEnlistment)
   at System.Transactions.VolatileEnlistmentPreparing.EnterState(InternalEnlistment enlistment)
   at System.Transactions.VolatileEnlistmentActive.ChangeStatePreparing(InternalEnlistment enlistment)
   at System.Transactions.TransactionStateVolatilePhase1.EnterState(InternalTransaction tx)
   at System.Transactions.TransactionStatePhase0.EnterState(InternalTransaction tx)
   at System.Transactions.TransactionStateActive.BeginCommit(InternalTransaction tx, Boolean asyncCommit, AsyncCallback asyncCallback, Object asyncState)
   at System.Transactions.CommittableTransaction.Commit()
   at System.Transactions.TransactionScope.InternalDispose()
   at System.Transactions.TransactionScope.Dispose()
   at ConsoleApp3.Program4.<>c__DisplayClass4_1.<<Main>b__0>d.MoveNext() in xxx 
```

On **all** subsequent, the following exception is thrown when trying to enlist Rebus in the transaction:

```
System.InvalidOperationException occurred
  HResult=0x80131509
  Message=Cannot start a new ambient Rebus transaction because there is already one associated with the current execution context!
  Source=Rebus.TransactionScopes
  StackTrace:
   at Rebus.TransactionScopes.TransactionScopeExtensions.EnlistRebus(TransactionScope transactionScope)
   at ConsoleApp3.Program4.<>c__DisplayClass4_1.<<Main>b__0>d.MoveNext() in xxx
```

This renders the bus instance inoperable.

**Comment by mookid8000** [comment]
Hmmm.... it must be because `Dispose` throws an exception, and then Rebus does not get a chance to remove its ambient transaction.

For now – in case you're stuck and need to be able to recover from this situation – you can try and remove the ambient Rebus transaction by calling

    AmbientTransactionContext.SetCurrent(null);

to clear it. Alternatively – and I really recommend this, because it doen't seem like you're actually using `System.Transactions.TransactionScope` for anything – you should use Rebus' own transaction scope:

    using(var scope = new RebusTransactionScope())
    {
        stuff with the bus in here

        await scope.CompleteAsync();
        // or scope.Complete(); if that's better for you
    }

Then you can ditch the dependency on `System.Transactions` and all of its secret and weird ways of doing stuff.

**Comment by mookid8000** [comment]
Todo at this point:

- [ ] verify that the hypothesis about not clearing the transaction context holds
- [ ] move the issue to `Rebus.TransactionScopes` and make it be about being able to recover from a `Dispose` that throws (which is ILLEGAL, so it's pretty crazy that `TransactionScope` does it)

**Comment by nebelx** [comment]
Was able to reproduce that. Will try to fix

**Comment by nebelx** [comment]
@mookid8000, have you any notes on the fix ?

**Comment by mookid8000** [comment]
Try going here 👉 [yes here](https://github.com/rebus-org/Rebus.TransactionScopes/pull/1/files/126a7ac4dc80274137fc82da01ae0bdc3db60fce#diff-9ca058c8cb8ab30948d5f3033e2435b3L89)

**Comment by nebelx** [comment]
hmmm, It's link to my pull request, but no comments, no merges ...

**Comment by mookid8000** [comment]
Weird – on my machine, when I click the link I posted, I end up here:

![image](https://user-images.githubusercontent.com/32968/35636416-57b3f18e-06b1-11e8-9f5a-57e164cf070a.png)

I was wondering why you removed the `null`ification of the ambient transaction context.

**Comment by mookid8000** [comment]
Maybe if you click again? 😉

**Comment by nebelx** [comment]
unfortunately cant see your comment. Nevertheless answer to the question is : because it's being clened up when captured RebusTransactionScope is disposed.
https://github.com/rebus-org/Rebus/blob/master/Rebus/Transport/RebusTransactionScope.cs

**Comment by mookid8000** [comment]
That makes sense 😁 

I wonder why you cannot see it when I start a review for a PR that you made? Oh well, who cares.... I'll go merge it right away

**Comment by mookid8000** [comment]
(btw this was not an issue with the RabbitMQ transport – it was an issue with [Rebus.TransactionScopes](https://github.com/rebus-org/Rebus.TransactionScopes) which would could accidentally leave some crap behind if `Complete()` failed on the `System.Transactions.TransactionScope`.

It was fixed in rebus-org/Rebus.TransactionScopes#1
