### ISSUE TITLE
Ensure that quorum queues are supported

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/Rebus.RabbitMq#63]
not entirely sure what it is, though, but using them seems to result in the following exception:
```
Unhandled Exception: Rebus.Injection.ResolutionException: Could not resolve Rebus.Bus.IBus with decorator depth 0 - registrations: Rebus.Injection.Injectionist+Handler ---> RabbitMQ.Client.Exceptions.OperationInterruptedException: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=406, text="PRECONDITION_FAILED - inequivalent arg 'x-queue-type' for queue 'consumer' in vhost 'local_oh': received none but current is the value 'quorum' of type 'longstr'", classId=50, methodId=10, cause=

   at RabbitMQ.Client.Impl.SimpleBlockingRpcContinuation.GetReply(TimeSpan timeout)

   at RabbitMQ.Client.Impl.ModelBase.QueueDeclare(String queue, Boolean passive, Boolean durable, Boolean exclusive, Boolean autoDelete, IDictionary`2 arguments)

   at RabbitMQ.Client.Impl.AutorecoveringModel.QueueDeclare(String queue, Boolean durable, Boolean exclusive, Boolean autoDelete, IDictionary`2 arguments)

   at Rebus.RabbitMq.RabbitMqTransport.DeclareQueue(String address, IModel model, Boolean durable)

   at Rebus.RabbitMq.RabbitMqTransport.CreateQueue(String address)

   at Rebus.RabbitMq.RabbitMqTransport.Initialize()

   at Rebus.Config.RebusConfigurer.<>c__DisplayClass12_1.<Start>b__25(IResolutionContext c)

   at Rebus.Injection.Injectionist.Resolver`1.InvokeResolver(IResolutionContext context)

   at Rebus.Injection.Injectionist.ResolutionContext.Get[TService]()

   --- End of inner exception stack trace ---

   at Rebus.Injection.Injectionist.ResolutionContext.Get[TService]()

   at Rebus.Injection.Injectionist.Get[TService]()

   at Rebus.Config.RebusConfigurer.Start()
```
so maybe the solution is simply to enable customizing the properties passed to RabbitMQ when declaring things (exchange, queue, etc)

**Comment by mookid8000** [comment]
It already works: By customizing the input queue, passing an appropriate argument to it, the input queue can be declared of the "quorum" type:
```csharp
Configure.With(activator)
    .Transport(t =>
    {
        t.UseRabbitMq(connectionString, queueName)
            .InputQueueOptions(q => q.AddArgument("x-queue-type", "quorum"));
    })
    .Start();
```
which will result in 
![image](https://user-images.githubusercontent.com/32968/77287656-5b5f6100-6cd6-11ea-95b4-b712e756bda1.png)

CHeck out [this test](https://github.com/rebus-org/Rebus.RabbitMq/blob/master/Rebus.RabbitMq.Tests/WorksWithQuorumQueue.cs) for a working example.
